CREATE OR REPLACE PACKAGE UTL_DDL_SOURCE AS

  VERSION CONSTANT VARCHAR(50) := '0.0.1';

  FUNCTION EXTRACT_SOURCE(p_owner IN VARCHAR2, p_object_type IN VARCHAR2, p_object_name IN VARCHAR2) RETURN CLOB;
  
  FUNCTION EXTRACT_SOURCE(p_object_type IN VARCHAR2, p_object_name IN VARCHAR2) RETURN CLOB;
  
  FUNCTION EXTRACT_PURIFIED_SOURCE(p_owner IN VARCHAR2, p_object_type IN VARCHAR2, p_object_name IN VARCHAR2) RETURN CLOB;
  
  FUNCTION EXTRACT_PURIFIED_SOURCE(p_object_type IN VARCHAR2, p_object_name IN VARCHAR2) RETURN CLOB;
  
  FUNCTION HASH_SOURCE(p_owner IN VARCHAR2, p_object_type IN VARCHAR2, p_object_name IN VARCHAR2) RETURN RAW;
  
  FUNCTION HASH_SOURCE(p_object_type IN VARCHAR2, p_object_name IN VARCHAR2) RETURN RAW;
  
  FUNCTION HASH_PURIFIED_SOURCE(p_owner IN VARCHAR2, p_object_type IN VARCHAR2, p_object_name IN VARCHAR2) RETURN RAW;
  
  FUNCTION HASH_PURIFIED_SOURCE(p_object_type IN VARCHAR2, p_object_name IN VARCHAR2) RETURN RAW;

END UTL_DDL_SOURCE;
/
